// import localFont from 'next/font/local'
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from './Providers'
import {NextUIProvider} from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

// const bkBold = localFont({ src: './fonts/Flame-Bold.ttf' })
// const bkReg = localFont({ src: './fonts/Flame-Regular.ttf' })
// const bkSans = localFont({ src: './fonts/FlameSans-Regular.ttf' })

export const metadata = {
  title: "Tianxiao Zhang",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className} >
        <NextUIProvider><Providers>{children}</Providers></NextUIProvider>
        </body>
      </html>
    
      
  );
}
